### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ExcaroX** [JadaDev/Armor-Creator#1]
![image](https://user-images.githubusercontent.com/125036586/218586813-64c81cde-16a9-4afc-a455-0f10005e0a94.png)
do you know how i can fix this i think its mysql error ?

**Comment by JadaDev** [comment]
Run this using HeidiSQL into your database.
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ascent';
flush privileges; 
```
rename root and password to your own details.
That is caused because of your MySQL is using a different Authentication method.

**Comment by ExcaroX** [comment]
"root"@"localhost" what i need to use my mysqlroot password or ? if you can come discord ill be happy :D

**Comment by ExcaroX** [comment]
can you give me your discord bcs i need help i did that but again same error

**Comment by ExcaroX** [comment]
![image](https://user-images.githubusercontent.com/125036586/218760389-a7005f73-fc51-4e59-b82b-1bf451d0bd64.png)

**Comment by ExcaroX** [comment]
or should i just install mysql 5.7 ? i think the latest version is buggy ?

**Comment by ExcaroX** [comment]
I was talking with rocket and he told me you need to update the program to sup mysql 8 he thinks that 
![image](https://user-images.githubusercontent.com/125036586/218797366-cbd8b2e9-97c1-497c-9db9-facf6d2a452c.png)

**Comment by JadaDev** [comment]
He isn't wrong tho I'm keeping the old method as it has no issues at all the update itself isn't needed.

**Comment by JadaDev** [comment]
Well changes in Plan, decided to update to support latest MySQL Authentication!
